#!/bin/zsh

# 載入環境變數
source .env
echo "請拖入檔案："
read folderPath
cd $folderPath
#.zip 的上傳方法
echo "https://api.github.com/orgs/$ORG_NAME/repos"

for file in *.zip; do
  if [[ -f "$file" ]]; then
    # 解壓縮檔案
    repository_name="${file%.zip}"
    # 上傳檔案到 GitHub
    response=$(curl -L \
      -H "Accept: application/vnd.github+json" \
      -H "Authorization: Bearer $ACCESS_TOKEN"\
      -H "X-GitHub-Api-Version: 2022-11-28" \
      "https://api.github.com/repos/$ORG_NAME/$repository_name")
    repo_id=$(echo "$response" | jq -r '.id')
    wait
    if [ "$repo_id" = "null" ]; then
      echo "$repository_name"
    fi
  fi
done
