#!/bin/zsh

# 載入環境變數
source .env
echo "請拖入檔案："
read folderPath
cd $folderPath
#.zip 的上傳方法
echo "https://api.github.com/orgs/$ORG_NAME/repos"

for file in *.zip; do
  if [[ -f "$file" ]]; then
    # 解壓縮檔案
    unzip "$file"
    repository_name="${file%.zip}"
    cd "${file%.zip}"
    # 上傳檔案到 GitHub
    response=$(curl -L \
      -H "Accept: application/vnd.github+json" \
      -H "Authorization: Bearer $ACCESS_TOKEN"\
      -H "X-GitHub-Api-Version: 2022-11-28" \
      "https://api.github.com/repos/$ORG_NAME/$repository_name")
    repo_id=$(echo "$response" | jq -r '.id')
    echo $repo_id
    if [ "$repo_id" = "null" ]; then
      echo "新增Repo"
      curl -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer $ACCESS_TOKEN"\
        -H "X-GitHub-Api-Version: 2022-11-28" \
        "https://api.github.com/orgs/$ORG_NAME/repos" \
        -d "{\"name\":\"$repository_name\",\"description\":\"$repository_name\",\"private\":true"
    fi
    git init
    git checkout -b master
    git add .
    git commit -m "Initial commit"
    git remote add origin "git@github.com:$ORG_NAME/$repository_name.git"
    git push -u origin master && echo "完成上傳"
    wait
    cd ..
    # 刪除壓縮檔案和解壓縮後的檔案
    rm -rf "$repository_name"
  fi
done
